### ISSUE TITLE
update geocode page

### ISSUE THREAD

**Issue by JennaLynGallagher** [COS301-SE-2021/GeoCode#367]
- [x] Styling
- [x] Functionality
- [x] Connect to api

**Comment by JennaLynGallagher** [comment]
> We should be able to adapt the current geocode creation interface to use for updating as well.

But surely they won't change all details more just available and hints. I don't think we should allow them to change locations. Was just going to make a pop up or modal on the profile page

**Comment by robotic-coder** [comment]
Good point. Since the geocode profile page uses the new modular geocode details component, we can just add a hide-able button to it (same way the QR code button is currently implemented) to determine if an edit button should be visible. Then if it is clicked, bring up a modal for editing
