### ISSUE TITLE
Discord Bots creation

### ISSUE THREAD

**Issue by JennaLynGallagher** [COS301-SE-2021/GeoCode#4]

**Comment by robotic-coder** [comment]
@JennaLynGallagher @robotic-coder @Michael-Stroh @NitronBiohazard @CalebJohnstone this is a test

**Comment by robotic-coder** [comment]
@JennaLynGallagher @robotic-coder @Michael-Stroh @NitronBiohazard @CalebJohnstone this is another test

**Comment by robotic-coder** [comment]
Bot is up and running - it will notify us of pushes to master and repost issues/PRs into dedicated channels. These reposts will ping us on Discord if a PR/issue comment includes a ping on GitHub. @JennaLynGallagher
